### PR TITLE
Fix: fix no-unused-vars (fixes #44)

### LINKED ISSUE #44: Auto fixing produces wrong syntax.
I noticed is that `autofix/no-unused-vars` doesn't work well with object destructuring.

before autofix
```
const { name, email } = this.props // "name" is unused
```

after autofix
```
const { , email } = this.props
```

coma is left

With unused imports everything works great.

_Originally posted by @serhiipalash in https://github.com/aladdin-add/eslint-plugin-autofix/issues/33#issuecomment-500158744_

### PR DESCRIPTION
**Pull request by g-plane**

### CODE REVIEW

File: tests/lib/rules/no-unused-vars.js [hunk 1]
```diff
@@ -141,11 +141,6 @@ ruleTester.run("no-unused-vars", rule, {
             output: null,
             errors: [{ type: "Identifier" }]
         },
-        {
-            code: "var a = b = c()",
-            output: null,
-            errors: [{ type: "Identifier" }]
-        },
```
Comment (aladdin-add) [inline tests/lib/rules/no-unused-vars.js]: is it intentional to remove the case?

Comment (g-plane) [reply tests/lib/rules/no-unused-vars.js]: Yes, since it's unsafe:

```js
var a = b = c

fn(b)
```

Comment (aladdin-add) [reply tests/lib/rules/no-unused-vars.js]: IHMO, `var a = b = c();` => `b = c();`.

Comment (g-plane) [reply tests/lib/rules/no-unused-vars.js]: It can't.

```js
let b
let a = b = c

fn(b)
```

It will be fixed as below, which is invalid:

```js
let b
let b = c

fn(b)
```

File: tests/lib/rules/no-unused-vars.js [hunk 2]
```diff
@@ -141,6 +141,12 @@ ruleTester.run("no-unused-vars", rule, {
             output: null,
             errors: [{ type: "Identifier" }]
         },
+        {
+            code: "var [a, b] = c",
+            output: null,
+            parserOptions: { ecmaVersion: 6 },
+            errors: [{ type: "Identifier" }, { type: "Identifier" }]
+        },
```
Comment (aladdin-add) [inline tests/lib/rules/no-unused-vars.js]: seems it can also be fixed. an enhencement. :(

Comment (g-plane) [reply tests/lib/rules/no-unused-vars.js]: Array destructing is order-sensitive.

File: tests/lib/rules/no-unused-vars.js (hunk 1 above)
Comment (aladdin-add) [reply tests/lib/rules/no-unused-vars.js]:
```js
let a = b = c; //  => let a = (b = c);
```
so, the statement is to declare `a`, not `b` & `c`

Comment (g-plane) [reply tests/lib/rules/no-unused-vars.js]: I know, but that auto fixing will produce error.

File: tests/lib/rules/no-unused-vars.js (hunk 2 above)
Comment (aladdin-add) [reply tests/lib/rules/no-unused-vars.js]: that's to say, the fixer should not remove the commas.

File: tests/lib/rules/no-unused-vars.js (hunk 1 above)
Comment (aladdin-add) [reply tests/lib/rules/no-unused-vars.js]: I'm fine to not fix this case, but I don't think we should remove the case--just to prevent crashing

File: tests/lib/rules/no-unused-vars.js (hunk 2 above)
Comment (g-plane) [reply tests/lib/rules/no-unused-vars.js]: Done.
